### ISSUE TITLE
New 4th level Priest

### ISSUE THREAD

**Issue by Grammarsalad** [UnearthedArcana/B_Spells#171]
**Sticks to Snakes** (New; 2e pnp)  
(Alteration)

Level: 4  
Sphere: (Creation or Plant)
Range: Visual Range of Caster  
Duration: 2 rnds./level   
Casting Time: 7  
Area of Effect: 1 stick/level    
Saving Throw: None  

This spell changes 1 stick per level into snakes.  These snakes attack as commanded by the priest.  This spell can only be cast in a wilderness area, where sticks are plentiful.  

SNAKE STATS:REVISE
typical 2hd, AC6, Move 9, constricts or bite 1 point +poison

(ANIMATIONS???)   

***Notes***:

**Comment by GwendolyneFreddy** [comment]
This spell was (and still is) on my TODO list. If you need specific snakes animation, I can provide you with a SNAKE_SMALL animation (50 % or 75 % vanilla snake animation reduction).

**Comment by Grammarsalad** [comment]
Oh @GwendolyneFreddy
That would be awesome! What works best for you?

**Comment by GwendolyneFreddy** [comment]
As you wish.

Once back home, I can send you a MP at Beamdog's.

**Comment by Grammarsalad** [comment]
Perfect!
