### ISSUE TITLE
Bug during install on clean Bg2 EE

### ISSUE THREAD

**Issue by Majber** [UnearthedArcana/B_Spells#179]
Bug during install on clean Bg2 EE
Here is line with Error:

Copied [B_Spells/data/iwd_spells/wizard_5/IDSHROUD.pro] to [override/IDSHROUD.pro]
Added projectile file B_Spells/data/iwd_spells/wizard_5/IDSHROUD.pro
Copying 1 file ...
ERROR: error loading [B_Spells/data/iwd_spells/wizard_5/SOFLAMC.bam.BAM]
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Add New Spells -> Install All new spells (including IWDEE spells if applicable)], rolling back to previous state
Unable to Unlink [backup/B_Spells/101/OTHER.101]: Unix.Unix_error(1, "unlink", "backup/B_Spells/101/OTHER.101")
[backup/B_Spells/101/UNSETSTR.101] SET_STRING uninstall info not found
Will uninstall 561 files for [B_SPELLS/SETUP-B_SPELLS.TP2] component 101.
Uninstalled    561 files for [B_SPELLS/SETUP-B_SPELLS.TP2] component 101.
Unable to Unlink [backup/B_Spells/101/READLN.101]: Unix.Unix_error(20, "unlink", "backup/B_Spells/101/READLN.101")
Unable to Unlink [backup/B_Spells/101/READLN.101.TEXT]: Unix.Unix_error(20, "unlink", "backup/B_Spells/101/READLN.101.TEXT")
ERROR: Unix.Unix_error(20, "stat", "B_Spells/data/iwd_spells/wizard_5/SOFLAMC.bam.BAM")
Please make a backup of the file: SETUP-B_SPELLS.DEBUG and look for support at: Grammarsalad

And here is full file
[SETUP-B_SPELLS.txt](https://github.com/UnearthedArcana/B_Spells/files/4086984/SETUP-B_SPELLS.txt)

**Comment by Majber** [comment]
Thats bug from IWDEE spells ( I check for IWDEE only option)
For New Spells only its diffrent error:

Adding spell WIZARD_INVISIBILITY_TO_UNDEAD
Copying and patching 1 file ...
ERROR: error loading [B_Spells/data/new_spells/priest_1/B_W107.spl]
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Add New Spells -> Install New Spells only], rolling back to previous state
Will uninstall 237 files for [B_SPELLS/SETUP-B_SPELLS.TP2] component 103.
Uninstalled    237 files for [B_SPELLS/SETUP-B_SPELLS.TP2] component 103.
ERROR: Unix.Unix_error(20, "stat", "B_Spells/data/new_spells/priest_1/B_W107.spl")
Please make a backup of the file: SETUP-B_SPELLS.DEBUG and look for support at: Grammarsalad

**Comment by Grammarsalad** [comment]
Fixed "SOFLAMC.bam.BAM" error

**Comment by Grammarsalad** [comment]
Commented out Inv to undead for now
