### ISSUE TITLE
Latest release version 

### ISSUE THREAD

**Issue by Majber** [UnearthedArcana/B_Spells#180]
Is it save to use B_Spells Version 0.90.02 via download zip or we must use B_Spells Version 0.88.16 from "Latest releases"?

**Comment by Majber** [comment]
And if we must use latest release B_Spells Version 0.88.16 can you please fix latest version to be usable? 
(it contains a lot of fixes etc.)

**Comment by Grammarsalad** [comment]
Yeah, I definitely suggest using the most recent release version. 

I'll see about making the more recent version useable

**Comment by Grammarsalad** [comment]
Warning:

The next release won't have any* new items and likely won't have all of the new spells. 

*I do have a working (alpha) version of the priest scrolls component if you like. lt adds all priest spells as scrolls--even spells added by most mods if installed after them--and distributes them to be sold in all temples (that sell anything). You'll get some odd results, like maybe the temple of Lathander might sell an unholy word scroll, but yeah it's still in development

**Comment by Majber** [comment]
I would like to see just working version, more recent = better . I care mostly about new arcane spells. 

So if you could make it work without much husslen some new spells would be great. 
Do you have any ETA for new version?

**Comment by Grammarsalad** [comment]
I'm working on it right now.  Hopefully, I'll have a version you can _install_ shortly.  I can't guarantee that it'll be bug free...

@Majber What other mods are you planning on installing?

**Comment by Majber** [comment]
only https://github.com/Holic75/Baldurs-gate-dnd-3.5

Its main "thing" its to convert rules to dnd 3,5.
I hope this 2 mods will work together. I can't decide what order should be better, any thoughts?

**Comment by Grammarsalad** [comment]
Oh, that's a great mod.  I haven't looked into making my mods compatible with it, though...

okay, looking at the readme, I'm somewhat concerned about the Empower Magic and Extend Magic feats.  My guess, my hope is that @Holic75 handles spells automatically (not unlike how I handle priest spell scrolls).  In that case, it would be best to install B_Spells _before_ BGDND3.5.  Otherwise, you could probably install B_Spells _after_ BGDND3.5 (but, assuming it works at all, those feats will probably _not_ work for my spells).

**Comment by Majber** [comment]
I will try to install B_Spells before BGDND3.5, (that new version that you work on) and I will see if I got any errors. If yes I will just disable Empower Magic and Extend Magic feats somehow.

**Comment by Grammarsalad** [comment]
Okay, I've fixed the first error you found, and I've removed the Invis to undead wiz spell for now.  Looking for more errors but hopefully should be ready soon

**Comment by Grammarsalad** [comment]
Okay, its about ready.  There is some issue with priest spell scrolls, so I need to leave that out for now as well.  Also, when you get the message, "*Please be patient.  This will take some time..." I _really_ mean it.   That section takes a minimum of 5-10 minutes.  It's driving me crazy, but it is necessary.  

New version should be up in about 30 minutes or so.  I'll let you know

**Comment by Grammarsalad** [comment]
Here it is:

https://github.com/UnearthedArcana/B_Spells/releases/tag/0.90.03

Let me know if you have any issues (and enjoy!)

**Comment by Majber** [comment]
1. One question: that new added spells -> where we can find them?
Can we buy them from vendors, for example Ribald at the Adventurer's mart ?

2. Also, second question (not this mod related but you are experienced modder so maybe you have knowledge about it): is it possible to mod unlearn (and then learn new) spells functionality for sorcerers or edit their spells in notepad++ ( I dont want to use NearInfnity, becouse of breaking some scripts/save)

**Comment by Grammarsalad** [comment]
1. They should be sold in various stores.  I'm going to need to look through the code and get back to you.  I know that, while I have been distributing scrolls to various stores and NPCs in a random and haphazard manner, my plan is to go back to do it all a bit more sensibly.  

One thing I am sure of--and I apologize that I didn't think to mention it before now--is that not all wiz scrolls will be available in a given game.  As such, if there is a spell that you really want, try to pick it up at character creation (if you're a mage or bard--sorcerers should be fine.)  

2. It depends what you want to do.  Is this a PC?  I'm not sure what the issue with AI would be, but if so it _seems_ like it would be fine to do this in NearInfinity.  If this is an npc, and you want them to use the spell on their own, that can be a bit tricky...

**Comment by Grammarsalad** [comment]
Okay, it looks like a lot of the IWDEE spells have been distributed to Sorcerous Sundries, High Hedge, and a store with the filename "SCROLLS.sto".  I think that the first two are BGEE only, but the third  _Might_ be the scroll store in the district just after Irenicus' dungeon.  I don't think it's the Adventurer's mart.   I can't check which store that is (at work).  I'm not sure if Ribald sells any (that would have been an obvious choice for placement--note to self).  

Many of the new spells are sold in the underdark (especially the store named "UDDROW25.STO").

**Comment by Majber** [comment]
Ok, thank you. That's all I need.
bdw.-> Mod install without errors, and after that dnd 3,5 mod without errors too. :)

**Comment by Majber** [comment]
Hi, I noticed that you opened a lot of issues with new spells? or not? Im confused a little, but my question is -how close is it to new major release?

**Comment by Grammarsalad** [comment]
Heh, sorry, I didn't see this until now.  

It's ... not very close to a new major release.  It'll be done sometime, but likely not in 2020.
