### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Majber** [UnearthedArcana/B_Spells#196]
Hi, I have quick question. How long untill new version? I want to start new game, and I dont want start again when new version drops.

**Comment by Grammarsalad** [comment]
@Majber 
Ahh, you should probably start that game.  It's going to be a bit.  Like, probably more than 6 months (even though it looks like with this caronavirus thing, I'll have a bit more mod time)  
Edit: 
I have a few balls in the air.  Like, way too many.  Also, I have a short attention span.  What were we talking about? :P

**Comment by Majber** [comment]
ok, thank you :)
