### ISSUE TITLE
8 25 24 Master: New spells refused to install on BGEE!

### ISSUE THREAD

**Issue by Endarire** [UnearthedArcana/B_Spells#218]
Greetings, @Grammarsalad!

Below is the error message I received when trying to install only the new spells from this mod on BGEE.  The only other mods were DLCMerger and the pre-EET Start mods.

Thankee!

![image](https://github.com/user-attachments/assets/784d914d-820a-46da-b33d-4886c0716e61)

**Comment by Grammarsalad** [comment]
Known
