### ISSUE TITLE
Feral Instinct

### ISSUE THREAD

**Issue by Grammarsalad** [UnearthedArcana/B_Spells#34]
Make it 50% attack nearest creature, 50% flee in terror (i.e. fight or flight)

**Comment by Grammarsalad** [comment]
...i think i want to change it back to murderous command.

**Comment by loldrup** [comment]
and this only works on animals?
very cool for a druid/ranger spell!

**Comment by Grammarsalad** [comment]
The spell in essence "reverts" the target to an animalistic state. 

Actually, murderous command will be cleric only (only attack) whereas feral instinct will be druid only with fight or flight (animal domain)

**Comment by loldrup** [comment]
It sounds like you assume the precense of other mods. Which mods are those?
(I say this because you used the term 'Animal Domain')
⁣

Den 15. jan. 2018 13.38, fra 13.38, Grammarsalad <notifications@github.com> skrev:

**Comment by Grammarsalad** [comment]
I don't assume the presence of other mods, but I'm going out of my way to make this mod compatible with Spell Revisions (which is kind of a pita due to the way spells are implemented in SR--Compatibility with (e.g.) will be much easier because they use ADD_SPELL.  

But, heh, the use of the word 'domain' was a (Freudian?) slip.  I meant 'sphere'

**Comment by Grammarsalad** [comment]
Added both feral instinct (druid only) and murderous command (cleric only).
